import "./globals.css";
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import QueryProvider from "@/components/query-client_provider";

const roboto = Roboto_Mono({
   weight: ["400", "700"],
   style: ["italic", "normal"],
   display: "auto",
   subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" suppressHydrationWarning>
         <head />
         <body className={`${roboto.className} antialiased min-h-screen`}>
            <QueryProvider>
               <ThemeProvider
                  attribute="class"
                  defaultTheme="dark"
                  enableSystem
                  disableTransitionOnChange
               >
                  <SidebarProvider defaultOpen={false}>
                     <div className="w-full h-full relative">{children}</div>
                  </SidebarProvider>
               </ThemeProvider>
            </QueryProvider>
         </body>
      </html>
   );
}
