import type { Metadata } from "next";
import { Balsamiq_Sans } from "next/font/google";
import "./globals.css";

const balsamiq = Balsamiq_Sans({
   weight: ["400", "700"],
   style: ["italic", "normal"],
   display: "auto",
   subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className="light">
         <body className={`${balsamiq.className} antialiased min-h-screen`}>
            {children}
         </body>
      </html>
   );
}
